# Generated by Django 4.2.6 on 2025-04-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_app', '0002_books_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(max_length=300, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('science_fiction', 'Science Fiction'), ('historical', 'Historical'), ('biography', 'Biography'), ('self_help', 'Self Help'), ('horror', 'Horror'), ('poetry', 'Poetry'), ('adventure', 'Adventure'), ('young_adult', 'Young Adult'), ('children', 'Children'), ('drama', 'Drama')], max_length=100),
        ),
    ]
