# Generated by Django 4.2.6 on 2025-04-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_app', '0004_alter_books_options_reading_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading_list',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
