# Generated by Django 4.2.6 on 2025-04-10 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Books_app', '0005_alter_reading_list_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading_list',
            options={'ordering': ['-position']},
        ),
        migrations.AlterUniqueTogether(
            name='reading_list',
            unique_together={('user', 'book')},
        ),
    ]
